
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.4.0
 * Query Engine version: ab56fe763f921d033a6c195e7ddeb3e255bdbb57
 */
Prisma.prismaVersion = {
  client: "7.4.0",
  engine: "ab56fe763f921d033a6c195e7ddeb3e255bdbb57"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AdminScalarFieldEnum = {
  id: 'id',
  email: 'email',
  passwordHash: 'passwordHash',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudioScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  email: 'email',
  phone: 'phone',
  logoUrl: 'logoUrl',
  brandingConfig: 'brandingConfig',
  subscriptionTier: 'subscriptionTier',
  subscriptionExpiresAt: 'subscriptionExpiresAt',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  billingModel: 'billingModel',
  commissionRate: 'commissionRate',
  commissionType: 'commissionType',
  currency: 'currency',
  defaultTerms: 'defaultTerms',
  taxRate: 'taxRate',
  address: 'address',
  city: 'city',
  state: 'state',
  zipCode: 'zipCode',
  website: 'website',
  description: 'description',
  isPublic: 'isPublic',
  hotDeal: 'hotDeal',
  isRecommended: 'isRecommended'
};

exports.Prisma.CommissionScalarFieldEnum = {
  id: 'id',
  studioId: 'studioId',
  bookingId: 'bookingId',
  invoiceId: 'invoiceId',
  amount: 'amount',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.StudioRequestScalarFieldEnum = {
  id: 'id',
  studioName: 'studioName',
  ownerName: 'ownerName',
  email: 'email',
  phone: 'phone',
  city: 'city',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  studioId: 'studioId',
  email: 'email',
  phone: 'phone',
  passwordHash: 'passwordHash',
  name: 'name',
  role: 'role',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  provider: 'provider',
  providerId: 'providerId'
};

exports.Prisma.CustomerScalarFieldEnum = {
  id: 'id',
  studioId: 'studioId',
  name: 'name',
  email: 'email',
  phone: 'phone',
  metadata: 'metadata',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  globalUserId: 'globalUserId'
};

exports.Prisma.ServiceScalarFieldEnum = {
  id: 'id',
  studioId: 'studioId',
  name: 'name',
  description: 'description',
  price: 'price',
  durationMinutes: 'durationMinutes',
  isActive: 'isActive',
  sortOrder: 'sortOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  coverImage: 'coverImage',
  occasion: 'occasion',
  categoryId: 'categoryId'
};

exports.Prisma.BookingScalarFieldEnum = {
  id: 'id',
  studioId: 'studioId',
  customerId: 'customerId',
  serviceId: 'serviceId',
  assignedToUserId: 'assignedToUserId',
  scheduledAt: 'scheduledAt',
  status: 'status',
  customerNotes: 'customerNotes',
  internalNotes: 'internalNotes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  acceptedTerms: 'acceptedTerms',
  contractUrl: 'contractUrl',
  quoteAcceptedAt: 'quoteAcceptedAt',
  quoteAmount: 'quoteAmount',
  quoteNotes: 'quoteNotes',
  quotedAt: 'quotedAt',
  quoteRejectionNotes: 'quoteRejectionNotes'
};

exports.Prisma.BookingStatusLogScalarFieldEnum = {
  id: 'id',
  bookingId: 'bookingId',
  status: 'status',
  notes: 'notes',
  createdAt: 'createdAt'
};

exports.Prisma.InvoiceScalarFieldEnum = {
  id: 'id',
  studioId: 'studioId',
  bookingId: 'bookingId',
  customerId: 'customerId',
  invoiceNumber: 'invoiceNumber',
  lineItems: 'lineItems',
  subtotal: 'subtotal',
  tax: 'tax',
  discount: 'discount',
  total: 'total',
  status: 'status',
  dueDate: 'dueDate',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PaymentScalarFieldEnum = {
  id: 'id',
  invoiceId: 'invoiceId',
  amount: 'amount',
  paymentMethod: 'paymentMethod',
  transactionId: 'transactionId',
  notes: 'notes',
  paidAt: 'paidAt'
};

exports.Prisma.PortfolioItemScalarFieldEnum = {
  id: 'id',
  studioId: 'studioId',
  title: 'title',
  description: 'description',
  imageUrl: 'imageUrl',
  category: 'category',
  sortOrder: 'sortOrder',
  isVisible: 'isVisible',
  createdAt: 'createdAt'
};

exports.Prisma.CategoryScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  imageUrl: 'imageUrl',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  studioId: 'studioId',
  customerId: 'customerId',
  bookingId: 'bookingId',
  rating: 'rating',
  comment: 'comment',
  reply: 'reply',
  isVisible: 'isVisible',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WorkflowScalarFieldEnum = {
  id: 'id',
  studioId: 'studioId',
  name: 'name',
  trigger: 'trigger',
  actions: 'actions',
  isActive: 'isActive',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.SubscriptionTier = exports.$Enums.SubscriptionTier = {
  STARTER: 'STARTER',
  PROFESSIONAL: 'PROFESSIONAL',
  STUDIO: 'STUDIO',
  ENTERPRISE: 'ENTERPRISE',
  PRO: 'PRO'
};

exports.StudioStatus = exports.$Enums.StudioStatus = {
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED',
  TRIAL: 'TRIAL'
};

exports.BillingModel = exports.$Enums.BillingModel = {
  SUBSCRIPTION: 'SUBSCRIPTION',
  COMMISSION: 'COMMISSION'
};

exports.CommissionType = exports.$Enums.CommissionType = {
  PERCENTAGE: 'PERCENTAGE',
  FIXED: 'FIXED'
};

exports.CommissionStatus = exports.$Enums.CommissionStatus = {
  PENDING: 'PENDING',
  COLLECTED: 'COLLECTED',
  CANCELLED: 'CANCELLED'
};

exports.StudioRequestStatus = exports.$Enums.StudioRequestStatus = {
  PENDING: 'PENDING',
  REVIEWED: 'REVIEWED',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED'
};

exports.UserRole = exports.$Enums.UserRole = {
  OWNER: 'OWNER',
  PHOTOGRAPHER: 'PHOTOGRAPHER',
  ASSISTANT: 'ASSISTANT',
  CUSTOMER: 'CUSTOMER'
};

exports.BookingStatus = exports.$Enums.BookingStatus = {
  INQUIRY: 'INQUIRY',
  QUOTED: 'QUOTED',
  CONFIRMED: 'CONFIRMED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.InvoiceStatus = exports.$Enums.InvoiceStatus = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
  OVERDUE: 'OVERDUE',
  CANCELLED: 'CANCELLED'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  CASH: 'CASH',
  BANK_TRANSFER: 'BANK_TRANSFER',
  UPI: 'UPI',
  CARD: 'CARD',
  OTHER: 'OTHER'
};

exports.Prisma.ModelName = {
  Admin: 'Admin',
  Studio: 'Studio',
  Commission: 'Commission',
  StudioRequest: 'StudioRequest',
  User: 'User',
  Customer: 'Customer',
  Service: 'Service',
  Booking: 'Booking',
  BookingStatusLog: 'BookingStatusLog',
  Invoice: 'Invoice',
  Payment: 'Payment',
  PortfolioItem: 'PortfolioItem',
  Category: 'Category',
  Review: 'Review',
  Workflow: 'Workflow'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
